### ISSUE TITLE
想问个问题 希望能给点建议

### ISSUE THREAD

**Issue by originzyf** [Guolei1130/BoardView#1]
![qq 20180328120359 00-00-02--00-00-05](https://user-images.githubusercontent.com/17819772/38008281-6add3770-3280-11e8-908e-0e2121b1e48b.gif)
我现在在做文件夹管理的功能 拖拽到左上角的时候  就删除的功能
但是拖上左上角  就脱离了recycleview的范围  就获取不到这个item的坐标了 没办法判断 他挪到哪了
希望大佬给点建议 谢谢

**Comment by Guolei1130** [comment]
可以获取到MotionEvent，根据MotionEvent的位置去做判断就可以

**Comment by originzyf** [comment]
我给最外层的布局添加了setOnDragListener 然后监听dragevent的布局 实现了这个功能 谢谢你的回答
